import Navigation from "@/components/shared/Navigation";
import "./globals.css";
import { OrderProvider } from "@/context/OrderProvider";
import { Toaster } from "@/components/ui/sonner";
import Footer from "@/components/shared/Footer";
import Layout from "@/components/shared/Layout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <OrderProvider>
          <Layout>{children}</Layout>
          <Toaster richColors />
        </OrderProvider>
      </body>
    </html>
  );
}
