import Navigation from "@/components/shared/Navigation";
import "./globals.css";
import { OrderProvider } from "@/context/OrderProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <OrderProvider>
        <body>{children}</body>
      </OrderProvider>
    </html>
  );
}
